spring:
  application:
    name: processing-service

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/pulsestack
    username: pulsestack
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://127.0.0.1:5432/pulsestack
    user: pulsestack
    password: password

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: processing-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "dev.pulsestack.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: "dev.pulsestack.domain.model.NewsItem"

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    dev.pulsestack: DEBUG
    org.springframework.kafka: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
